version: '3'

services:
  fronted:
    build: fronted
    ports:
      - 3000:3000
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - application=backendname

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=userapp
      - POSTGRES_DB=db
