version: '3.8'

services:
  fronted:
    build: frontend
    ports:
      - 3000:3000
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - application=backendname
    restart: always

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db

# docker run --name some-postgres -p 5432:5432 -e POSTGRES_PASSWORD=root -e POSTGRES_USER=postgres -e POSTGRES_DB=db -d postgres